name: Pull Request Validation

on:
  pull_request:
    branches: [ "main" ]

jobs:
  evaluate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # ---- Run solution on PR branch ----
      - name: Run PR solution
        run: |
          python scripts/solution.py --employees_path data/employees.csv --connections_path data/connections.csv --output_path pr_submission.csv

      - name: Evaluate PR accuracy
        id: eval_pr
        run: |
          PR_SCORE=$(python dependencies/evaluate.py --ground_truth data/ground_truth_managers.csv --submission pr_submission.csv)
          echo "pr_score=$PR_SCORE" >> $GITHUB_OUTPUT

      # ---- Run solution on main branch ----
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Install dependencies (main)
        run: pip install -r requirements.txt

      - name: Run main solution
        run: |
          python scripts/solution.py --employees_path data/employees.csv --connections_path data/connections.csv --output_path main_submission.csv

      - name: Evaluate main accuracy
        id: eval_main
        run: |
          MAIN_SCORE=$(python dependencies/evaluate.py --ground_truth data/ground_truth_managers.csv --submission main_submission.csv)
          echo "main_score=$MAIN_SCORE" >> $GITHUB_OUTPUT

      # ---- Post PR comment ----
      - name: Comment PR results
        uses: actions/github-script@v7
        with:
          script: |
            const prScore = "${{ steps.eval_pr.outputs.pr_score }}";
            const mainScore = "${{ steps.eval_main.outputs.main_score }}";
            const improved = Number(prScore) >= Number(mainScore);
            const message = `
                  ### ✅ Automated Model Evaluation

                  | Metric | Main | PR Branch |
                  |--------|------|-----------|
                  | Accuracy | ${mainScore} | ${prScore} |

                  Status: **${improved ? "✔️ Improved / Equal" : "❌ Regression"}**  
                  `;

                              github.rest.issues.createComment({
                                issue_number: context.issue.number,
                                owner: context.repo.owner,
                                repo: context.repo.repo,
                                body: message
                              });

                        # ---- Fail job if accuracy worsens ----
                        - name: Fail if PR accuracy worsens
                          if: ${{ steps.eval_pr.outputs.pr_score < steps.eval_main.outputs.main_score }}
                          run: exit 1
