- name: Comment PR results
  uses: actions/github-script@v7
  with:
    github-token: ${{ secrets.GH_TOKEN }}
    script: |
      const prScore = Number("${{ steps.eval_pr.outputs.pr_score }}");
      const mainScore = Number("${{ steps.eval_main.outputs.main_score }}");
      const verdict = prScore > mainScore
        ? "✔️ Improved"
        : (prScore === mainScore ? "➖ No change" : "❌ Regression");

      const body = `
### Automated Evaluation

| Metric   | Main | PR |
|---------|-----:|---:|
| Accuracy | ${mainScore}% | ${prScore}% |

**Verdict:** ${verdict}
`;

      await github.rest.issues.createComment({
        owner: context.repo.owner,
        repo: context.repo.repo,
        issue_number: context.issue.number,
        body
      });
